# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogo_velha.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets

col1 = ''
col2 = ''
col3 = ''
col4 = ''
col5 = ''
col6 = ''
col7 = ''
col8 = ''


class Ui_frm_jogo_da_velha(object):
    def setupUi(self, frm_jogo_da_velha):
        frm_jogo_da_velha.setObjectName("frm_jogo_da_velha")
        frm_jogo_da_velha.resize(420, 136)
        self.rd_1 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_1.setGeometry(QtCore.QRect(10, 10, 51, 25))
        self.rd_1.setText("")
        self.rd_1.setObjectName("rd_1")
        self.rd_2 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_2.setGeometry(QtCore.QRect(70, 10, 51, 25))
        self.rd_2.setText("")
        self.rd_2.setObjectName("rd_2")
        self.rd_3 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_3.setGeometry(QtCore.QRect(130, 10, 51, 25))
        self.rd_3.setText("")
        self.rd_3.setObjectName("rd_3")
        self.rd_4 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_4.setGeometry(QtCore.QRect(10, 50, 51, 25))
        self.rd_4.setText("")
        self.rd_4.setObjectName("rd_4")
        self.rd_5 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_5.setGeometry(QtCore.QRect(70, 50, 51, 25))
        self.rd_5.setText("")
        self.rd_5.setObjectName("rd_5")
        self.rd_6 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_6.setGeometry(QtCore.QRect(130, 50, 51, 25))
        self.rd_6.setText("")
        self.rd_6.setObjectName("rd_6")
        self.rd_7 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_7.setGeometry(QtCore.QRect(10, 90, 51, 25))
        self.rd_7.setText("")
        self.rd_7.setObjectName("rd_7")
        self.rd_8 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_8.setGeometry(QtCore.QRect(70, 90, 51, 25))
        self.rd_8.setText("")
        self.rd_8.setObjectName("rd_8")
        self.rd_9 = QtWidgets.QPushButton(frm_jogo_da_velha)
        self.rd_9.setGeometry(QtCore.QRect(130, 90, 51, 25))
        self.rd_9.setText("")
        self.rd_9.setObjectName("rd_9")
        self.lb_1 = QtWidgets.QLabel(frm_jogo_da_velha)
        self.lb_1.setGeometry(QtCore.QRect(10, 120, 161, 17))
        self.lb_1.setObjectName("lb_1")
        self.label = QtWidgets.QLabel(frm_jogo_da_velha)
        self.label.setGeometry(QtCore.QRect(210, 30, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frm_jogo_da_velha)
        self.label_2.setGeometry(QtCore.QRect(210, 80, 71, 21))
        self.label_2.setObjectName("label_2")
        self.txt_jogador1 = QtWidgets.QLineEdit(frm_jogo_da_velha)
        self.txt_jogador1.setGeometry(QtCore.QRect(280, 30, 113, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.txt_jogador1.setFont(font)
        self.txt_jogador1.setObjectName("txt_jogador1")
        self.txt_jogador2 = QtWidgets.QLineEdit(frm_jogo_da_velha)
        self.txt_jogador2.setGeometry(QtCore.QRect(280, 80, 113, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.txt_jogador2.setFont(font)
        self.txt_jogador2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_jogador2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.txt_jogador2.setObjectName("txt_jogador2")
        self.label_3 = QtWidgets.QLabel(frm_jogo_da_velha)
        self.label_3.setGeometry(QtCore.QRect(400, 30, 21, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frm_jogo_da_velha)
        self.label_4.setGeometry(QtCore.QRect(400, 80, 21, 21))
        self.label_4.setObjectName("label_4")
        self.rb_1 = QtWidgets.QRadioButton(frm_jogo_da_velha)
        self.rb_1.setEnabled(True)
        self.rb_1.setGeometry(QtCore.QRect(200, 160, 61, 23))
        self.rb_1.setAutoFillBackground(True)
        self.rb_1.setChecked(True)
        self.rb_1.setObjectName("rb_1")
        self.rb_2 = QtWidgets.QRadioButton(frm_jogo_da_velha)
        self.rb_2.setEnabled(True)
        self.rb_2.setGeometry(QtCore.QRect(270, 160, 61, 23))
        self.rb_2.setAutoFillBackground(True)
        self.rb_2.setChecked(False)
        self.rb_2.setObjectName("rb_2")

        self.retranslateUi(frm_jogo_da_velha)
        QtCore.QMetaObject.connectSlotsByName(frm_jogo_da_velha)

    def retranslateUi(self, frm_jogo_da_velha):
        _translate = QtCore.QCoreApplication.translate
        frm_jogo_da_velha.setWindowTitle(_translate(
            "frm_jogo_da_velha", "####   Jogo da Velha   ####"))
        self.lb_1.setText(_translate(
            "frm_jogo_da_velha", "<html><head/><body><p><span style=\" font-size:7pt;\">Desenvolvido por Giuliano Vianna</span></p></body></html>"))
        self.label.setText(_translate("frm_jogo_da_velha", "Jogador 1:"))
        self.label_2.setText(_translate("frm_jogo_da_velha", "Jogador 2:"))
        self.label_3.setText(_translate(
            "frm_jogo_da_velha", "<html><head/><body><p><span style=\" color:#1a5fb4;\">X</span></p></body></html>"))
        self.label_4.setText(_translate(
            "frm_jogo_da_velha", "<html><head/><body><p><span style=\" color:#1a5fb4;\">O</span></p></body></html>"))
        self.rb_1.setText(_translate("frm_jogo_da_velha", "Regra"))
        self.rb_2.setText(_translate("frm_jogo_da_velha", "Regra"))


############################## Botões #################################################

        self.rd_1.clicked.connect(self.bt1)
        self.rd_2.clicked.connect(self.bt2)
        self.rd_3.clicked.connect(self.bt3)
        self.rd_4.clicked.connect(self.bt4)
        self.rd_5.clicked.connect(self.bt5)
        self.rd_6.clicked.connect(self.bt6)
        self.rd_7.clicked.connect(self.bt7)
        self.rd_8.clicked.connect(self.bt8)
        self.rd_9.clicked.connect(self.bt9)

    ############################## Coluna 1 - Campo 1 #################################################

    def bt1(self):

        if self.rb_1.isChecked():
            self.rd_1.setText('X')
            self.rb_2.setChecked(True)
            self.rd_1.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            print('Linha 1: ' + col1)
            print('Linha 4: ' + col4)
            print('Linha 7: ' + col7)

        else:
            self.rd_1.setText('O')
            self.rb_1.setChecked(True)
            self.rd_1.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            print('Linha 1: ' + col1)
            print('Linha 4: ' + col4)
            print('Linha 7: ' + col7)

        if col1 == 'XXX' or col4 == 'XXX' or col7 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()

        elif col1 == 'OOO' or col4 == 'OOO' or col7 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()


############################## Coluna 1 - Campo 2 #################################################


    def bt2(self):

        if self.rb_1.isChecked():
            self.rd_2.setText('X')
            self.rb_2.setChecked(True)
            self.rd_2.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            print('Linha 1: ' + col1)
            print('linha 5: ' + col5)

        else:
            self.rd_2.setText('O')
            self.rb_1.setChecked(True)
            self.rd_2.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            print('Linha 1: ' + col1)
            print('Linha 5: ' + col5)

        if col1 == 'XXX' or col5 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col1 == 'OOO' or col5 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()

############################## Coluna 1 - Campo 3 #################################################

    def bt3(self):

        if self.rb_1.isChecked():
            self.rd_3.setText('X')
            self.rb_2.setChecked(True)
            self.rd_3.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 1: ' + col1)
            print('Linha 6: ' + col6)
            print('Linha 8: ' + col8)

        else:
            self.rd_3.setText('O')
            self.rb_1.setChecked(True)
            self.rd_3.setDisabled(True)
            col1 = self.rd_1.text() + self.rd_2.text() + self.rd_3.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 1: ' + col1)
            print('Linha 6: ' + col6)
            print('Linha 8: ' + col8)

        if col1 == 'XXX' or col6 == 'XXX' or col8 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col1 == 'OOO' or col6 == 'OOO' or col8 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()


############################## Coluna 2 - Campo 1  #################################################

    def bt4(self):

        if self.rb_1.isChecked():
            self.rd_4.setText('X')
            self.rb_2.setChecked(True)
            self.rd_4.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            print('Linha 2: ' + col2)
            print('Linha 4: ' + col4)
        else:
            self.rd_4.setText('O')
            self.rb_1.setChecked(True)
            self.rd_4.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            print('Linha 2: ' + col2)
            print('Linha 4: ' + col4)

        if col2 == 'XXX' or col4 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col2 == 'OOO' or col4 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()

############################## Coluna 2 - Campo 2  #################################################

    def bt5(self):

        if self.rb_1.isChecked():
            self.rd_5.setText('X')
            self.rb_2.setChecked(True)
            self.rd_5.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 2: ' + col2)
            print('Linha 5: ' + col5)
            print('Linha 7: ' + col7)
            print('Linha 8: ' + col8)

        else:
            self.rd_5.setText('O')
            self.rb_1.setChecked(True)
            self.rd_5.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 2: ' + col2)
            print('Linha 5: ' + col5)
            print('Linha 7: ' + col7)
            print('Linha 8: ' + col8)

        if col2 == 'XXX' or col5 == 'XXX' or col7 == 'XXX' or col8 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col2 == 'OOO' or col5 == 'OOO' or col7 == 'OOO' or col8 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()

############################## Coluna 2 - Campo 3  #################################################

    def bt6(self):

        if self.rb_1.isChecked():
            self.rd_6.setText('X')
            self.rb_2.setChecked(True)
            self.rd_6.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            print('linha 2: ' + col2)
            print('Linha 6: ' + col6)
        else:
            self.rd_6.setText('O')
            self.rb_1.setChecked(True)
            self.rd_6.setDisabled(True)
            col2 = self.rd_4.text() + self.rd_5.text() + self.rd_6.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            print('linha 2: ' + col2)
            print('Linha 6: ' + col6)

        if col2 == 'XXX' or col6 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col2 == 'OOO' or col6 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()

############################## Coluna 3 - Campo 1  #################################################

    def bt7(self):

        if self.rb_1.isChecked():
            self.rd_7.setText('X')
            self.rb_2.setChecked(True)
            self.rd_7.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 3: ' + col3)
            print('Linha 4: ' + col4)
            print('Linha 8: ' + col8)

        else:
            self.rd_7.setText('O')
            self.rb_1.setChecked(True)
            self.rd_7.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col4 = self.rd_1.text() + self.rd_4.text() + self.rd_7.text()
            col8 = self.rd_3.text() + self.rd_5.text() + self.rd_7.text()
            print('Linha 3: ' + col3)
            print('Linha 4: ' + col4)
            print('Linha 8: ' + col8)

        if col3 == 'XXX' or col4 == 'XXX' or col8 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col3 == 'OOO' or col4 == 'OOO' or col8 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()

############################## Coluna 3 - Campo 2  #################################################

    def bt8(self):

        if self.rb_1.isChecked():
            self.rd_8.setText('X')
            self.rb_2.setChecked(True)
            self.rd_8.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            print('Linha 3: ' + col3)
            print('Linha 5: ' + col5)

        else:
            self.rd_8.setText('O')
            self.rb_1.setChecked(True)
            self.rd_8.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col5 = self.rd_2.text() + self.rd_5.text() + self.rd_8.text()
            print('Linha 3: ' + col3)
            print('Linha 5: ' + col5)

        if col3 == 'XXX' or col5 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col3 == 'OOO' or col5 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()


############################# Coluna 3 - Campo 3  #################################################

    def bt9(self):

        if self.rb_1.isChecked():
            self.rd_9.setText('X')
            self.rb_2.setChecked(True)
            self.rd_9.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            print('Linha 3: ' + col3)
            print('Linha 6: ' + col6)
            print('Linha 7: ' + col7)

        else:
            self.rd_9.setText('O')
            self.rb_1.setChecked(True)
            self.rd_9.setDisabled(True)
            col3 = self.rd_7.text() + self.rd_8.text() + self.rd_9.text()
            col6 = self.rd_3.text() + self.rd_6.text() + self.rd_9.text()
            col7 = self.rd_1.text() + self.rd_5.text() + self.rd_9.text()
            print('Linha 3: ' + col3)
            print('Linha 6: ' + col6)
            print('Linha 7: ' + col7)

        if col3 == 'XXX' or col6 == 'XXX' or col7 == 'XXX':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 1 é o Vencedor!')
            x = msg1.exec_()
        elif col3 == 'OOO' or col6 == 'OOO' or col7 == 'OOO':
            msg1 = QMessageBox()
            msg1.setWindowTitle('Confirmação')
            msg1.setText('Jogador 2  é o Vencedor!')
            x = msg1.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_jogo_da_velha = QtWidgets.QWidget()
    ui = Ui_frm_jogo_da_velha()
    ui.setupUi(frm_jogo_da_velha)
    frm_jogo_da_velha.show()
    sys.exit(app.exec_())
